### ISSUE TITLE
include center cell?

### ISSUE THREAD

**Issue by semibran** [hughsk/moore#2]
hey, I was just doing some stuff with [Delannoy numbers](https://en.wikipedia.org/wiki/Delannoy_number) when I noticed that neighborhoods usually include the center cell. from wikipedia:

> The Moore neighbourhood of a cell is the cell itself and the cells at a Chebyshev distance of 1.

> The von Neumann neighbourhood of a cell is the cell itself and the cells at a Manhattan distance of 1.

I understand that the center cell doesn't usually hold much value when working with neighborhoods, but it may be a good idea to include it for accuracy. thoughts?

**Comment by hughsk** [comment]
Hey @semibran, good catch! While it might be more accurate this way, it does make things a bit clunkier in the case where a user isn't checking the origin cell.

``` javascript
const full = moore(2, 2)

for (var i = 0; i < full.length; i++) {
  var cell = full[i]
  if (!cell[0] && !cell[1]) {
    // ...
  }
}
```

Whereas if we exclude it, it can easily be added to the resulting array in the cases where we do want to check for it:

``` javascript
const full = moore(2, 2).concat([0, 0])
```

One solution for both cases would be to make it opt-in, maintaining backwards compatibility:

``` javascript
// one of:
const full = moore(2, 2, true)
const full = moore(2, 2, { origin: true })
```

But I personally lean more to documenting the behaviour in the readme as it keeps the code simple. Your call :)

**Comment by semibran** [comment]
after some extra research (i.e. page 2 of search results. Wow), it looks like sources other than wolfram and wikipedia suggest that the origin cell can be omitted - stuff like "contains 8 or 9 neighbors, depending on whether the center cell is included".

I'd still prefer keeping it for accuracy and simplicity:

- the hacky skip conditional `i < length / 2 ? i : i + 1` could be omitted
- `moore(r, d).length` would equal `(2r + 1) ^ d`, and `vonNeumann(r, d).length` would equal `delannoy(d, r)`; notice that the signatures don't match up there, but that's a discussion for another time :grimacing:

Also, like you said, the origin cell can be easily added to the resulting array, so I think adding an extra parameter would be unnecessary.

I guess either route is fine but including the center cell seems to fit the original definition better. In the end it's your call :))
